version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10.0.0
    working_directory: ~/chika-cesium

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/chika-cesium

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm install
      - run:
          command: |
            set +eo
            npm ls
            true
      - persist_to_workspace:
          root: ~/chika-cesium
          paths:
            - node_modules
  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash) -t b940bea3-f20b-4f8e-8cdd-c8064231a2b3
  compile:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run compile
      - persist_to_workspace:
          root: ~/chika-cesium
          paths:
            - lib
  test_lib:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          command: npm test -- -u
          environment:
            LIB_DIR: lib

workflows:
  version: 2
  build:
    jobs:
      - setup
      - compile:
          requires:
            - setup
      - test_lib:
          requires:
            - compile
      - test:
          requires:
            - setup
      - lint:
          requires:
            - setup
